site_name: IoT Dokumentacja projektu

theme:
  name: "material"

plugins:
  - mkdocstrings


nav:
  - index.md
  - Podział pracy: responsibilities.md
  - Wybór technologii: selected_technologies.md
  - Collector Executor: collector_executor_documentation.md
  - Data2Metric: data2metric_documentation.md
  - Discovery: discoverer_documentation.md
  - Guardain: guardian_documentation.md
  - Grafana: grafana_documentation.md
  - Generator: generator_documentation.md
  - API: api.md
  - GUI: gui.md
  - Infrastruktura chmurowa: infra.md
